
version: "2.2"

x-lens2-environment: &lens2-environment
  DATAOS_FQDN: cheerful-maggot.dataos.app
  LENS2_NAME: device-360
  LENS2_DESCRIPTION: "Ecommerce use case on Adventureworks sales data"
  LENS2_TAGS: "lens2, ecom, sales and customer insights"
  LENS2_AUTHORS: ""
  LENS2_SCHEDULED_REFRESH_TIMEZONES: "UTC,America/Vancouver,America/Toronto"
  LENS2_SOURCE_TYPE: minerva
  LENS2_SOURCE_NAME: system
  LENS2_SOURCE_CATALOG_NAME: icebase
  DATAOS_RUN_AS_APIKEY: "API-key"
  LENS2_LOG_LEVEL: error
  CACHE_LOG_LEVEL: "trace"
  LENS2_DEV_MODE: true
  LENS2_DEV_MODE_PLAYGROUND: false
  LENS2_REFRESH_WORKER: true
  LENS2_SCHEMA_PATH: model
  LENS2_PG_SQL_PORT: 5432
  CACHE_DATA_DIR: "/var/work/.store"
  NODE_ENV: production
  LENS2_ALLOW_UNGROUPED_WITHOUT_PRIMARY_KEY: "true"

services:
  api:
    restart: always
    image: rubiklabs/lens2:0.35.18-50
    ports:
      - 4000:4000
      - 25432:5432
    environment:
      <<: *lens2-environment   
    volumes:
      - ./model:/etc/dataos/work/model
    